version: '3.8'

services:
  bitcoin-wallet:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NETWORK=testnet 
      - BLOCKCHAIN_API_URL=https://blockstream.info/testnet/api  
      - MAINNET_API_URL=https://blockstream.info/api 
    networks:
      - bitcoin-net
      - zabbix-net
    volumes:
      - wallet_data:/app/data  

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-6.4-latest
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=zabbix-db
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - POSTGRES_DB=zabbix
    depends_on:
      - zabbix-db
    networks:
      - zabbix-net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-6.4-latest
    ports:
      - "80:8080"
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=zabbix-db
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - POSTGRES_DB=zabbix
    depends_on:
      - zabbix-server
      - zabbix-db
    networks:
      - zabbix-net

  zabbix-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - POSTGRES_DB=zabbix
    volumes:
      - zabbix_data:/var/lib/postgresql/data
    networks:
      - zabbix-net

  zabbix-agent:
    image: zabbix/zabbix-agent2:ubuntu-6.4-latest
    environment:
      - ZBX_HOSTNAME=bitcoin-wallet
      - ZBX_SERVER_HOST=zabbix-server
    depends_on:
      - zabbix-server
    networks:
      - zabbix-net
    volumes:
      - ./zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro

networks:
  bitcoin-net:
  zabbix-net:

volumes:
  wallet_data:  
  zabbix_data:  